/* - - - -

   테이블 생성

   - - - - */
-- 나라 테이블
CREATE TABLE COUNTRIES (
    "CODE" NUMBER PRIMARY KEY,
    "COUNTRY_NAME" VARCHAR2(400 BYTE) UNIQUE NOT NULL
);
INSERT INTO COUNTRIES VALUES (82, 'KR'); -- 한국


-- 카테고리테이블
CREATE TABLE CATEGORIES (
    "NO" NUMBER PRIMARY KEY,
    "TAG" VARCHAR2(400 BYTE) UNIQUE NOT NULL
);
CREATE SEQUENCE CATEGORIES_NO_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '공지'); --1
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '이벤트'); --2
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '기타'); --3
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '선택안함'); --4
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '가사도우미'); --5
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '청소도우미'); --6
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '등하원도우미'); --7
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '요리도우미'); --8
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '산후도우미'); --9
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '식당도우미'); --10
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '육아도우미'); --11
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '펫시터'); --12
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '베이비시터'); --13
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '요양보호사'); --14
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '대리티켓구매'); --15
INSERT INTO CATEGORIES (NO, TAG) VALUES (CATEGORIES_NO_SEQ.nextval, '직구대행'); --16


-- 브랜드 테이블
CREATE TABLE BRANDS (
    "NO" NUMBER PRIMARY KEY,
    "NAME" VARCHAR2(400 BYTE) UNIQUE NOT NULL
);
CREATE SEQUENCE BRANDS_NO_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;


-- 지역테이블
CREATE TABLE LOCATIONS (
    "NO" NUMBER PRIMARY KEY,
    "FIRST_NAME" CLOB NOT NULL,
    "SECOND_NAME" CLOB
);
CREATE SEQUENCE LOCATIONS_NO_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;
-- 지번_강원도
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '강릉시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '고성군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '동해시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '삼척시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '속초시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '양구군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '양양군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '영월군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '원주시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '인제군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '정선군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '철원군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '춘천시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '태백시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '평창군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '홍천군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '화천군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '강원도', '횡성군');

-- 지번_경기도
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '가평군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '고양시 덕양구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '고양시 일산동구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '고양시 일산서구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '과천시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '광명시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '광주시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '구리시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '군포시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '김포시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '남양주시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '동두천시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '부천시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '성남시 분당구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '성남시 수정구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '성남시 중원구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '수원시 권선구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '수원시 영통구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '수원시 장안구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '수원시 팔달구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '시흥시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '안산시 단원구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '안산시 상록구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '안성시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '안양시 동안구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '안양시 만안구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '양주시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '양평군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '여주시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '연천군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '오산시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '용인시 기흥구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '용인시 수지구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '용인시 처인구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '의왕시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '의정부시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '이천시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '파주시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '평택시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '포천시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '하남시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '화성시');

-- 지번_경상남도
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '거제시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '거창군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '고성군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '김해시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '남해군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '밀양시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '사천시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '산청군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '양산시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '의령군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '진주시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '창녕군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '창원시 마산합포구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '창원시 마산회원구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '창원시 성산구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '창원시 의창구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '창원시 진해구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '통영시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '하동군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '함안군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '함양군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상남도', '합천군');

-- 지번_경상북도
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '경산시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '경주시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '고령군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '구미시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '군위군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '김천시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '문경시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '봉화군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '상주시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '성주군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '안동시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '영덕군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '영양군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '영주시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '영천시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '예천군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '울릉군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '울진군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '의성군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '청도군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '청송군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '칠곡군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '포항시 남구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경상북도', '포항시 북구');

-- 지번_광주광역시
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '광주광역시', '광산구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '광주광역시', '남구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '광주광역시', '동구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '광주광역시', '북구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '광주광역시', '서구');

-- 지번_대구광역시
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '대구광역시', '남구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '대구광역시', '달서구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '대구광역시', '달성군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '대구광역시', '동구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '대구광역시', '북구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '대구광역시', '서구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '대구광역시', '수성구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '대구광역시', '중구');

-- 지번_대전광역시
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '대전광역시', '대덕구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '대전광역시', '동구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '대전광역시', '서구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '대전광역시', '유성구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '대전광역시', '중구');

-- 지번_부산광역시
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '강서구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '금정구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '기장군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '남구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '동구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '동래구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '부산진구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '북구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '사상구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '사하구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '서구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '수영구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '연제구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '영도구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '중구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '부산광역시', '해운대구');

-- 지번_서울특별시
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '강남구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '강동구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '강북구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '강서구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '관악구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '광진구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '구로구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '금천구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '노원구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '도봉구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '동대문구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '동작구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '마포구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '서대문구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '서초구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '성동구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '성북구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '송파구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '양천구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '영등포구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '용산구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '은평구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '종로구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '중구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '서울특별시', '중랑구');
-- INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '경기도', '하남시');

-- 지번_세종특별자치시
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '세종특별자치시', '세종시');

-- 지번_울산광역시
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '울산광역시', '남구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '울산광역시', '동구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '울산광역시', '북구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '울산광역시', '울주군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '울산광역시', '중구');

-- 지번_인천광역시
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '인천광역시', '강화군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '인천광역시', '계양구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '인천광역시', '남동구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '인천광역시', '동구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '인천광역시', '미추홀구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '인천광역시', '부평구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '인천광역시', '서구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '인천광역시', '연수구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '인천광역시', '옹진군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '인천광역시', '중구');

-- 지번_전라남도
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '강진군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '고창군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '고흥군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '곡성군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '광양시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '구례군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '나주시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '담양군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '목포시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '무안군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '보성군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '순천시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '신안군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '여수시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '영광군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '영암군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '완도군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '장성군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '장흥군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '진도군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '함평군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '해남군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라남도', '화순군');

-- 지번_전라북도
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '고창군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '군산시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '김제시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '남원시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '무주군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '부안군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '순창군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '완주군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '익산시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '임실군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '장수군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '전주시 덕진구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '전주시 완산구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '정읍시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '전라북도', '진안군');

-- 지번_제주특별자치도
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '제주특별자치도', '서귀포시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '제주특별자치도', '제주시');

-- 지번_충청남도
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '계룡시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '공주시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '금산군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '논산시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '당진시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '보령시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '부여군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '서산시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '서천군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '아산시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '예산군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '천안시 동남구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '천안시 서북구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '청양군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '태안군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청남도', '홍성군');

-- 지번_충청북도
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청북도', '괴산군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청북도', '단양군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청북도', '보은군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청북도', '영동군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청북도', '옥천군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청북도', '음성군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청북도', '제천시');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청북도', '증평군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청북도', '진천군');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청북도', '청주시 상당구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청북도', '청주시 서원구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청북도', '청주시 청원구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청북도', '청주시 흥덕구');
INSERT INTO LOCATIONS(NO, FIRST_NAME, SECOND_NAME) VALUES (LOCATIONS_NO_SEQ.nextval, '충청북도', '충주시');

COMMIT;


-- 유저테이블
CREATE TABLE USERS (
    "NO" NUMBER PRIMARY KEY,
    -- auto-increment
    "NAME" VARCHAR2(20 BYTE) NOT NULL,
    "NICK" VARCHAR2(20 BYTE) UNIQUE NOT NULL,
    "ID" VARCHAR2(20 BYTE) UNIQUE NOT NULL,
    "PW" VARCHAR2(20 BYTE) NOT NULL,
    "GENDER" NUMBER(1) DEFAULT 2 NOT NULL,
    "BIRTH_YY" NUMBER,
    "BIRTH_MM" NUMBER,
    "BIRTH_DD" NUMBER,
    "EMAIL" VARCHAR2(100 BYTE) NOT NULL,
    "POINT" NUMBER(6) DEFAULT 0,
    "GRADE" VARCHAR2(20) DEFAULT '새싹',
    "LOCATION_NO" NUMBER,
    "LOCATION_ADDR" CLOB DEFAULT '',
    "LOCATION_DETAIL" CLOB DEFAULT '',
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "COUNTRY_CODE" NUMBER,
    FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRIES(CODE),
    FOREIGN KEY (LOCATION_NO) REFERENCES LOCATIONS(NO),
    CONSTRAINT USER_GENDER_CK CHECK (GENDER IN(0, 1, 2))
);
CREATE SEQUENCE USERS_NO_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;
INSERT INTO USERS (NO, NAME, NICK, ID, PW, GENDER, EMAIL, COUNTRY_CODE) VALUES (USERS_NO_SEQ.nextval, 'GM.행복이', 'GM.행복이', 'ADMIN_01', 'admin1234', 2, 'the_helper@www.com', 82);
INSERT INTO USERS (NO, NAME, NICK, ID, PW, GENDER, EMAIL, COUNTRY_CODE) VALUES (USERS_NO_SEQ.nextval, '사용자1', '사용자1', 'user01', '1234', 2, 'user1@www.com', 82);
INSERT INTO USERS (NO, NAME, NICK, ID, PW, GENDER, EMAIL, COUNTRY_CODE) VALUES (USERS_NO_SEQ.nextval, '사용자2', '사용자2', 'user02', '1234', 2, 'user2@www.com', 82);


-- 구인게시판글 테이블
CREATE TABLE JOB_BOARD (
    "NO" NUMBER PRIMARY KEY ,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "CREATOR_NO" NUMBER NOT NULL,
    "CATEGORY" NUMBER,
    "TITLE" CLOB NOT NULL,
    "TIME_DAY" TIMESTAMP NOT NULL,
    "TIME_START" TIMESTAMP NOT NULL,
    "TIME_END" TIMESTAMP NOT NULL,
    "LOCATION_NO" NUMBER NOT NULL,
    "LOCATION_ADDR" CLOB NOT NULL,
    "LOCATION_DETAIL" VARCHAR2(200 BYTE) NOT NULL,
    "PAY" NUMBER(7) NOT NULL,
    "NUM_OF_PEOPLE" NUMBER(1),
    "DETAIL" CLOB,
    "PART_TIMER_LIST" CLOB,

    FOREIGN KEY (CREATOR_NO) REFERENCES USERS(NO),
    FOREIGN KEY (CATEGORY) REFERENCES CATEGORIES(NO),
    FOREIGN KEY (LOCATION_NO) REFERENCES LOCATIONS(NO)
);
CREATE SEQUENCE JOB_BOARD_NO_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;
INSERT INTO JOB_BOARD (NO, CREATED_AT, CREATOR_NO, CATEGORY, TITLE, TIME_DAY, TIME_START, TIME_END, LOCATION_NO, LOCATION_ADDR, LOCATION_DETAIL, PAY, NUM_OF_PEOPLE, DETAIL, PART_TIMER_LIST) VALUES (JOB_BOARD_NO_SEQ.nextval, TO_TIMESTAMP('2021-05-22 06:04:36.841000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 1, 15, 'BTS콘서트 티켓팅 해줄 분 구해요!', TO_TIMESTAMP('2021-05-27 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), TO_TIMESTAMP('2021-05-01 10:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), TO_TIMESTAMP('2021-05-01 11:30:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 99, '경상북도 울릉군 울릉읍 독도이사부길 63', ' 이사부길', 10000, 1, '신의손 구해요!', null);
INSERT INTO JOB_BOARD (NO, CREATED_AT, CREATOR_NO, CATEGORY, TITLE, TIME_DAY, TIME_START, TIME_END, LOCATION_NO, LOCATION_ADDR, LOCATION_DETAIL, PAY, NUM_OF_PEOPLE, DETAIL, PART_TIMER_LIST) VALUES (JOB_BOARD_NO_SEQ.nextval, TO_TIMESTAMP('2021-05-24 02:15:04.997000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 2, 12, '푸들 일일 펫시터 구합니다', TO_TIMESTAMP('2021-05-27 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), TO_TIMESTAMP('2021-05-01 10:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), TO_TIMESTAMP('2021-05-01 23:30:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 131, '부산광역시 부산진구 새싹로 245', '(초읍동) ㅋㅋ', 50000, 1, '강아지키우고 있으신분만 지원 가능해여!', null);
INSERT INTO JOB_BOARD (NO, CREATED_AT, CREATOR_NO, CATEGORY, TITLE, TIME_DAY, TIME_START, TIME_END, LOCATION_NO, LOCATION_ADDR, LOCATION_DETAIL, PAY, NUM_OF_PEOPLE, DETAIL, PART_TIMER_LIST) VALUES (JOB_BOARD_NO_SEQ.nextval, TO_TIMESTAMP('2021-05-25 02:55:27.954000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 1, 16, '미국 직구 대행 구해요', TO_TIMESTAMP('2021-05-27 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), TO_TIMESTAMP('2021-05-01 10:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), TO_TIMESTAMP('2021-05-01 11:30:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 155, '서울특별시 서초구 반포대로 3', '(서초동) 테스트', 50000, 1, '미국 직구 대행 구합니다', null);
INSERT INTO JOB_BOARD (NO, CREATED_AT, CREATOR_NO, CATEGORY, TITLE, TIME_DAY, TIME_START, TIME_END, LOCATION_NO, LOCATION_ADDR, LOCATION_DETAIL, PAY, NUM_OF_PEOPLE, DETAIL, PART_TIMER_LIST) VALUES (JOB_BOARD_NO_SEQ.nextval, TO_TIMESTAMP('2021-05-25 07:59:03.294000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 3, 5, '가사도우미 구해요 ', TO_TIMESTAMP('2021-05-30 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), TO_TIMESTAMP('2021-05-01 08:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), TO_TIMESTAMP('2021-05-01 17:30:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 153, '서울특별시 마포구 월드컵북로42나길 7', '(상암동, 대교빌라) 월드커', 70000, 1, '가사도우미 경험 있는분으로 하루동안 구합니다', null);
INSERT INTO JOB_BOARD (NO, CREATED_AT, CREATOR_NO, CATEGORY, TITLE, TIME_DAY, TIME_START, TIME_END, LOCATION_NO, LOCATION_ADDR, LOCATION_DETAIL, PAY, NUM_OF_PEOPLE, DETAIL, PART_TIMER_LIST) VALUES (JOB_BOARD_NO_SEQ.nextval, TO_TIMESTAMP('2021-05-25 08:00:54.011000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 2, 13, '베이비 시터 구해용', TO_TIMESTAMP('2021-05-27 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), TO_TIMESTAMP('2021-05-01 04:30:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), TO_TIMESTAMP('2021-05-01 06:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 136, '부산광역시 수영구 광안로 9', '(광안동) 테스트444', 4444, 1, '아기가 순하고 돌보기 순해요ㅎㅎ 베이비시터 경험있는분으로 구함니당!',  null);
INSERT INTO JOB_BOARD (NO, CREATED_AT, CREATOR_NO, CATEGORY, TITLE, TIME_DAY, TIME_START, TIME_END, LOCATION_NO, LOCATION_ADDR, LOCATION_DETAIL, PAY, NUM_OF_PEOPLE, DETAIL, PART_TIMER_LIST) VALUES (JOB_BOARD_NO_SEQ.nextval, TO_TIMESTAMP('2021-05-25 19:32:24.576000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 3, 6, '이사청소도우미 구합니다 ', TO_TIMESTAMP('2021-05-27 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), TO_TIMESTAMP('2021-05-01 06:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), TO_TIMESTAMP('2021-05-01 14:30:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 131, '부산광역시 부산진구 새싹로 245', '(초읍동) ㅁ', 80000, 1, '이사 청소 도우미 구해요!', null);

-- 후기 게시판글 테이블
CREATE TABLE REVIEW_BOARD (
    "NO" NUMBER PRIMARY KEY,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "CREATOR_NO" NUMBER NOT NULL,
    "TITLE" CLOB NOT NULL,
    "HITS" NUMBER(5) DEFAULT 0,
    "REVIEW_SCORE" NUMBER(1) DEFAULT 0,
    "DETAIL" CLOB,
    "JOB_POST_NO" NUMBER NOT NULL,

    FOREIGN KEY (CREATOR_NO) REFERENCES USERS(NO),
    FOREIGN KEY (JOB_POST_NO) REFERENCES JOB_BOARD(NO)
);
CREATE SEQUENCE REVIEW_BOARD_NO_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;


-- 공지게시판글 테이블
CREATE TABLE NOTIFY_BOARD (
    "NO" NUMBER PRIMARY KEY,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "CREATOR_NO" NUMBER NOT NULL,
    "TITLE" CLOB NOT NULL,
    "HITS" NUMBER(6) DEFAULT 0,
    "DETAIL" CLOB,
    "CATEGORY" VARCHAR(30) DEFAULT 0,
    CONSTRAINT CATEGORY_CK CHECK("CATEGORY" IN('이벤트','필독공지','사용자제제')),

    FOREIGN KEY (CREATOR_NO) REFERENCES USERS(NO)
);
CREATE SEQUENCE NOTIFY_BOARD_NO_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;


-- 상품 테이블
CREATE TABLE PRODUCTS (
    "NO" NUMBER PRIMARY KEY,
    "NAME" CLOB NOT NULL,
    "AMOUNT" NUMBER(4) DEFAULT 0,
    "PRICE" NUMBER(6) NOT NULL,
    "BRAND" NUMBER NOT NULL,
    "PRODUCT_IMAGE" BLOB,
    "DETAIL" CLOB,

    FOREIGN KEY (BRAND) REFERENCES BRANDS(NO)
);
CREATE SEQUENCE PRODUCTS_NO_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;


-- 스크랩테이블 (구인게시글만 스크랩합니다.)
CREATE TABLE SCRAPS (
    "USER_NO" NUMBER NOT NULL,
    "POST_NO" NUMBER NOT NULL,

    FOREIGN KEY (USER_NO) REFERENCES USERS(NO),
    FOREIGN KEY (POST_NO) REFERENCES JOB_BOARD(NO)
);


-- 지원현황테이블
CREATE TABLE VOLUNTEERS (
    "USER_NO" NUMBER NOT NULL,
    "POST_NO" NUMBER NOT NULL,
    "STATE" NUMBER(1) DEFAULT 0 NOT NULL,
--     0 : CONSIDER , 1 : ACCEPT , 2 : FAIL

    FOREIGN KEY (USER_NO) REFERENCES USERS(NO),
    FOREIGN KEY (POST_NO) REFERENCES JOB_BOARD(NO)
);


-- 포인트 테이블
CREATE TABLE POINTS (
    "USER_NO" NUMBER NOT NULL ,
    "VALUE" NUMBER(6),
    "BOUGHT_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "DETAIL" CLOB,

    FOREIGN KEY (USER_NO) REFERENCES USERS(NO)
);


-- 구매내역 테이블
CREATE TABLE PURCHASES (
    "USER_NO" NUMBER NOT NULL,
    "PRODUCT_NO" NUMBER NOT NULL,
    "PURCHASE_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "PURCHASE_COUNT" NUMBER(4) NOT NULL,

    FOREIGN KEY (USER_NO) REFERENCES USERS(NO),
    FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCTS(NO)
);

COMMIT;

/* - - - -

   함수 생성

   - - - - */
-- 지역의 처음, 두번째 이름을 이용해서 no를 구해내는 함수
CREATE OR REPLACE FUNCTION GET_LOCATION_NO(location_first_name IN VARCHAR2, location_second_name IN VARCHAR2)
    RETURN NUMBER
    IS
    location_no NUMBER;
BEGIN

    SELECT NO
    INTO location_no
    FROM LOCATIONS
    WHERE FIRST_NAME LIKE location_first_name AND SECOND_NAME LIKE location_second_name;

    return location_no;
END;

-- 구인게시글의 나의 지원 상태를 가져오는 함수
CREATE OR REPLACE FUNCTION GET_VOLUNTEER_STATE(user_no IN NUMBER, job_no IN NUMBER)
    RETURN VARCHAR2
    IS
    user_state VARCHAR2(200);
    st         NUMBER;
BEGIN

    user_state := ' ';

    SELECT STATE
    INTO st
    FROM VOLUNTEERS
    WHERE USER_NO = GET_VOLUNTEER_STATE.user_no
      AND POST_NO = job_no;

    CASE
        WHEN st = 0 THEN
            user_state := '고려중';
        WHEN st = 1 THEN
            user_state := '승인';
        WHEN st = 2 THEN
            user_state := '실패';
        END CASE;

    RETURN user_state;

EXCEPTION
    WHEN OTHERS THEN
        RETURN user_state;
END;


-- 해당 구인게시글의 '승인'이 된 사람 인원수 출력
CREATE OR REPLACE FUNCTION GET_WORKER_COUNT(job_no IN NUMBER)
    RETURN NUMBER
    IS
    worker_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO worker_count FROM VOLUNTEERS WHERE POST_NO = job_no AND STATE = 1;
    return worker_count;
END;

    COMMIT ;

    /* - - - -

프로시저 생성

   - - - - */
-- public int register(UserBean user)
CREATE OR REPLACE PROCEDURE ADD_USER(name IN VARCHAR2, nick IN VARCHAR2, id IN VARCHAR2, pw IN VARCHAR2,
gender IN NUMBER, birth_yy IN NUMBER, birth_mm IN NUMBER, birth_dd IN NUMBER,
email IN VARCHAR2, location_first_name IN VARCHAR2, location_second_name IN VARCHAR2,
location_addr IN VARCHAR2, location_detail IN VARCHAR2)
IS
BEGIN

    IF ADD_USER.location_first_name IS NOT NULL
        THEN
        INSERT INTO USERS(NO, NAME, NICK, ID, PW, GENDER, BIRTH_YY, BIRTH_MM, BIRTH_DD, EMAIL, LOCATION_NO,
                          LOCATION_ADDR, LOCATION_DETAIL)
        VALUES (USERS_NO_SEQ.nextval, ADD_USER.name, ADD_USER.nick, ADD_USER.id, ADD_USER.pw, ADD_USER.gender,
                ADD_USER.birth_yy, ADD_USER.birth_mm, ADD_USER.birth_dd, ADD_USER.email,
                GET_LOCATION_NO(ADD_USER.location_first_name, ADD_USER.location_second_name),
                ADD_USER.location_addr, ADD_USER.location_detail);
    ELSE
        INSERT INTO USERS(NO, NAME, NICK, ID, PW, GENDER, BIRTH_YY, BIRTH_MM, BIRTH_DD, EMAIL)
        VALUES (USERS_NO_SEQ.nextval, ADD_USER.name, ADD_USER.nick, ADD_USER.id, ADD_USER.pw, ADD_USER.gender,
                ADD_USER.birth_yy, ADD_USER.birth_mm, ADD_USER.birth_dd, ADD_USER.email);
    COMMIT;
    END IF;
END;

-- public int deleteUser(String no)
CREATE OR REPLACE PROCEDURE DELETE_USER(user_no IN NUMBER)
IS
    user_id VARCHAR2(30);
BEGIN
    SELECT ID INTO user_id FROM USERS WHERE NO = user_no;

    IF user_id IS NOT NULL AND user_id NOT LIKE 'ADMIN_'
       THEN
           DELETE FROM SCRAPS WHERE USER_NO = DELETE_USER.user_no;
           DELETE FROM JOB_BOARD WHERE CREATOR_NO = user_no;
           DELETE FROM REVIEW_BOARD WHERE CREATOR_NO = user_no;
           DELETE FROM PURCHASES WHERE USER_NO = DELETE_USER.user_no;
           DELETE FROM USERS WHERE NO = user_no;
           COMMIT;
   END IF;
END;


-- public int updateUser(UserBean user)
CREATE OR REPLACE PROCEDURE MODIFY_USER(user_no IN NUMBER, user_pw IN VARCHAR2,
yy IN NUMBER, mm IN NUMBER, dd IN NUMBER, email IN VARCHAR2,
first_name IN VARCHAR2, second_name IN VARCHAR2,
addr IN VARCHAR2, detail IN VARCHAR2)
IS
BEGIN

    UPDATE USERS
        SET PW = user_pw,
            BIRTH_YY = yy,
            BIRTH_MM = mm,
            BIRTH_DD = dd,
            EMAIL = MODIFY_USER.email,
            LOCATION_NO = GET_LOCATION_NO(first_name, second_name),
            LOCATION_ADDR = addr,
            LOCATION_DETAIL = detail
    WHERE NO = user_no;

    COMMIT;
END;

    -- public boolean addPost(JobPostBean jp)
CREATE OR REPLACE PROCEDURE INSERT_JOB_POST(creator_no IN NUMBER, category IN NUMBER, title IN VARCHAR2,
                                            time_day IN VARCHAR2, time_start IN VARCHAR2, time_end IN VARCHAR2,
                                            location_first_name IN VARCHAR2, location_second_name IN VARCHAR2, location_addr IN VARCHAR2, location_detail IN VARCHAR2,
                                            pay IN NUMBER, num_of_people IN NUMBER, detail IN CLOB)
    IS
    BEGIN
        INSERT INTO JOB_BOARD (NO, CREATOR_NO, CATEGORY, TITLE, TIME_DAY, TIME_START, TIME_END, LOCATION_NO,
                               LOCATION_ADDR,
                               LOCATION_DETAIL, PAY, NUM_OF_PEOPLE, DETAIL)
        VALUES (JOB_BOARD_NO_SEQ.nextval,
                INSERT_JOB_POST.creator_no,
                INSERT_JOB_POST.category,
                INSERT_JOB_POST.title,
                TO_TIMESTAMP(INSERT_JOB_POST.time_day, 'yy-mm-dd'),
                TO_TIMESTAMP(INSERT_JOB_POST.time_start, 'HH24:MI'),
                TO_TIMESTAMP(INSERT_JOB_POST.time_end, 'HH24:MI'),
                GET_LOCATION_NO(location_first_name, location_second_name),
                INSERT_JOB_POST.location_addr,
                INSERT_JOB_POST.location_detail,
                INSERT_JOB_POST.pay,
                INSERT_JOB_POST.num_of_people,
                INSERT_JOB_POST.detail);

    END;



-- public boolean modifyPost(JobPostBean jp, String job_post_no)
CREATE OR REPLACE PROCEDURE MODIFY_JOB_POST(category IN NUMBER, title IN VARCHAR2,
                                            time_day IN VARCHAR2, time_start IN VARCHAR2, time_end IN VARCHAR2,
                                            location_first_name IN VARCHAR2, location_second_name IN VARCHAR2,
                                            location_addr IN VARCHAR2, location_detail IN VARCHAR2,
                                            pay IN NUMBER, num_of_people IN NUMBER, part_timer_list IN CLOB,
                                            detail IN CLOB, job_no IN NUMBER)
    IS
BEGIN
    UPDATE JOB_BOARD
    SET CATEGORY        = MODIFY_JOB_POST.category,
        TITLE           = MODIFY_JOB_POST.title,
        TIME_DAY        = TO_TIMESTAMP(MODIFY_JOB_POST.time_day, 'yy-mm-dd'),
        TIME_START      = TO_TIMESTAMP(MODIFY_JOB_POST.time_start, 'HH24:MI'),
        TIME_END        = TO_TIMESTAMP(MODIFY_JOB_POST.time_end, 'HH24:MI'),
        LOCATION_NO     = GET_LOCATION_NO(location_first_name, location_second_name),
        LOCATION_ADDR   = MODIFY_JOB_POST.location_addr,
        LOCATION_DETAIL = MODIFY_JOB_POST.location_detail,
        PAY             = MODIFY_JOB_POST.pay,
        NUM_OF_PEOPLE   = MODIFY_JOB_POST.num_of_people,
        PART_TIMER_LIST = MODIFY_JOB_POST.part_timer_list,
        DETAIL          = MODIFY_JOB_POST.detail
    WHERE NO = MODIFY_JOB_POST.job_no;
    COMMIT;
END;

COMMIT ;

/* - - - -

뷰 생성

   - - - - */
-- public UserBean getuser(String id)
CREATE OR REPLACE VIEW GET_USER_INFO AS
SELECT U.NO,
       U.NAME,
       U.NICK,
       U.ID,
       U.PW,
       U.GENDER,
       U.BIRTH_YY,
       U.BIRTH_DD,
       U.BIRTH_MM,
       U.EMAIL,
       U.POINT,
       U.GRADE,
       L.FIRST_NAME  AS "LOCATION_FRIST_NAME",
       L.SECOND_NAME AS "LOCATION_SECOND_NAME",
       U.LOCATION_ADDR,
       U.LOCATION_DETAIL,
       U.CREATED_AT,
       U.COUNTRY_CODE
FROM USERS U
         LEFT JOIN LOCATIONS L on U.LOCATION_NO = L.NO;

-- public ArrayList<JobPostSubBean> getList(String key, String value)
CREATE OR REPLACE VIEW BEFORE_GET_SUB_LIST AS
SELECT J.NO                              AS "JOB_NO",
       J.LOCATION_NO                     AS "JOB_LOCATION_NO",
       U.NO                              AS "CREATOR_NO",
       U.NICK                            AS "CREATOR_NICK",
       J.TITLE                           AS "JOB_TITLE",
       J.PAY                             AS "JOB_PAY",
       TO_CHAR(J.TIME_DAY, 'yyyy-MM-dd')   AS "JOB_DAY",
       TO_CHAR(J.TIME_START, 'HH24:MI')    AS "JOB_TIME_START",
       TO_CHAR(J.TIME_END, 'HH24:MI')      AS "JOB_TIME_END",
       J.CREATED_AT
FROM JOB_BOARD J
         JOIN USERS U ON J.CREATOR_NO = U.NO;

CREATE OR REPLACE VIEW GET_SUB_LIST AS
SELECT J.*,
       L.FIRST_NAME  AS "JOB_LOCATION_FIRST_NAME",
       L.SECOND_NAME AS "JOB_LOCATION_SECOND_NAME"
FROM BEFORE_GET_SUB_LIST J
         JOIN LOCATIONS L ON L.NO = J.JOB_LOCATION_NO;


-- public JobPostBean getPost(String job_post_no)
CREATE OR REPLACE VIEW BEFORE_GET_POST AS
SELECT J.NO                                    AS "JOB_NO",
       TITLE                                   AS "JOB_TITLE",
       TO_CHAR(J.CREATED_AT, 'yy-MM-dd hh:mi') AS "CREATED_AT",
       CREATOR_NO,
       CATEGORY,
       TO_CHAR(TIME_DAY, 'yyyy-MM-dd')         AS "JOB_DAY",
       TO_CHAR(TIME_START, 'HH24:MI')            AS "JOB_TIME_START",
       TO_CHAR(TIME_END, 'HH24:MI')              AS "JOB_TIME_END",
       L.FIRST_NAME                            AS "JOB_LOCATION_FIRST_NAME",
       L.SECOND_NAME                           AS "JOB_LOCATION_SECOND_NAME",
       J.LOCATION_ADDR                         AS "JOB_LOCATION_ADDR",
       J.LOCATION_DETAIL                       AS "JOB_LOCATION_DETAIL",
       NUM_OF_PEOPLE                           AS "JOB_NUM_OF_PEOPLE",
       PART_TIMER_LIST                         AS "JOB_PART_TIME_LIST",
       PAY                                     AS "JOB_PAY",
       DETAIL                                  AS "JOB_DETAIL"
FROM JOB_BOARD J
         JOIN LOCATIONS L ON L.NO = J.LOCATION_NO;

CREATE OR REPLACE VIEW GET_POST AS
SELECT J.*,
       U.NICK                                  AS "CREATOR_NICK",
       GRADE
FROM BEFORE_GET_POST J
         JOIN USERS U ON J.CREATOR_NO = U.NO;

CREATE OR REPLACE VIEW GET_MY_VOLUNTEER AS
SELECT USER_NO,
       POST_NO                                   AS "JOB_POST_NO",
       TO_CHAR(TIME_DAY, 'yyyy-MM-dd')           AS "JOB_DAY",
       TO_CHAR(TIME_START, 'HH24:MI')            AS "JOB_TIME_START",
       TO_CHAR(TIME_END, 'HH24:MI')              AS "JOB_TIME_END",
       TITLE                                     AS "JOB_TITLE",
       DECODE(STATE, 0, '고려중', 1, '승인', 2, '실패') AS "MY_STATE"
FROM VOLUNTEERS
         JOIN JOB_BOARD JB on JB.NO = VOLUNTEERS.POST_NO;